# Generated by Django 5.1.6 on 2025-02-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='expires_at',
            new_name='expired_data',
        ),
        migrations.RemoveField(
            model_name='code',
            name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='code_number',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
